# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 18:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magicmusic', '0002_track_blob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(blank=True, default='community/default-images/default-avatar.jpg', upload_to='community/user-avatars')),
                ('avatar_content_type', models.CharField(max_length=50)),
                ('header_image', models.FileField(blank=True, default='community/default-images/default-background.jpg', upload_to='community/user-backgrounds')),
                ('header_image_content_type', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, default="The user didn't add a bio...", max_length=200)),
                ('followings', models.ManyToManyField(blank=True, related_name='follower_profile_set', to='community.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='Add some descriptions...', max_length=200, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('songfile', models.FileField(blank=True, upload_to='community/songfiles')),
                ('songfile_content_type', models.CharField(max_length=50)),
                ('cover', models.FileField(blank=True, default='community/default-images/default-cover.jpg', upload_to='community/song-covers')),
                ('cover_content_type', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Profile')),
                ('liking_people', models.ManyToManyField(blank=True, related_name='liking_people_set', to='community.Profile')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='magicmusic.Workspace')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Song'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='community.Profile'),
        ),
    ]
