# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='creator_profile',
        ),
    ]
