# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(default='community/default-images/default-avatar.jpg', upload_to='community/user-avatars'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='header_image',
            field=models.FileField(default='community/default-images/default-background.jpg', upload_to='community/user-backgrounds'),
        ),
    ]
