# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover_picture',
        ),
        migrations.RemoveField(
            model_name='album',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='album',
            name='description',
        ),
        migrations.RemoveField(
            model_name='album',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='album',
            name='name',
        ),
        migrations.AddField(
            model_name='song',
            name='liking_profile',
            field=models.ManyToManyField(blank=True, related_name='liking_people_set', to='community.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, default='community/default-images/default-avatar.jpg', upload_to='community/user-avatars'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, default="The user didn't add a bio...", max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='header_image',
            field=models.FileField(blank=True, default='community/default-images/default-background.jpg', upload_to='community/user-backgrounds'),
        ),
        migrations.AlterField(
            model_name='song',
            name='description',
            field=models.CharField(blank=True, default='Add some descriptions...', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='songfile',
            field=models.FileField(blank=True, upload_to='community/songfiles'),
        ),
    ]
