# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20180426_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_content_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='header_image_content_type',
        ),
        migrations.RemoveField(
            model_name='song',
            name='cover_content_type',
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.ImageField(blank=True, default="The user didn't add a bio...", max_length=200, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='header_image',
            field=models.ImageField(blank=True, default='community/default-images/default-background.jpg', upload_to='community/user-backgrounds'),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover',
            field=models.ImageField(blank=True, default='community/default-images/default-cover.jpg', upload_to='community/song-covers'),
        ),
    ]
