# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20180426_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='community/default-images/default-avatar.jpg', upload_to='community/user-avatars'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, default="The user didn't add a bio...", max_length=200),
        ),
    ]
