# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20180426_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
