# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-24 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicmusic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='blob',
            field=models.TextField(blank=True, null=True),
        ),
    ]
